# Generated by Django 5.2.1 on 2025-05-24 01:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def create_initial_data(apps, schema_editor):
    Status = apps.get_model('app_name', "Status")
    Category = apps.get_model('app_name', 'Category')
    SubCategory = apps.get_model('app_name', 'SubCategory')

    Status.objects.create(name="Бизнес")
    Status.objects.create(name="Личное")
    Status.objects.create(name="Налог")

    infra = Category.objects.create(name="Инфраструктура")
    SubCategory.objects.create(category=infra, name="VPS")
    SubCategory.objects.create(category=infra, name="Proxy")

    marketing = Category.objects.create(name="Маркетинг")
    SubCategory.objects.create(category=marketing, name="Avito")
    SubCategory.objects.create(category=marketing, name="Farpost")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app_cash.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='MoveCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sum_operation', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_cash.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app_cash.status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app_cash.subcategory')),
                ('typeoperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeoperations', to='app_cash.typeoperation')),
            ],
            options={
                'verbose_name': 'Движение денежных средств',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecategories', to='app_cash.typeoperation'),
        ),
    ]
